run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  gosec:
    includes: []

linters:
  disable-all: true
  enable:
    - err113
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - goheader
    - gosec