# Variables
DOCKER_IMAGE := dariomader/iperf3
DOCKER_TAG := latest

.PHONY: docker-build docker-clean

docker-build:
	@echo "Building Docker iperf image..."
	docker build -t $(DOCKER_IMAGE):$(DOCKER_TAG) -f Dockerfile-iperf .

docker-clean:
	@echo "Cleaning up Docker iperf image..."
	docker rmi $(DOCKER_IMAGE):$(DOCKER_TAG)